spring:
  main:
    web-application-type: none

wiremock:
  server:
    stubs: classpath:/mappings

logging:
  level:
    org.springframework.cloud.contract.wiremock: debug
    org.springframework.web.client: debug
    com.github.tomakehurst.wiremock: trace

